routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    $user = Session::get('userinfo');
    if($user != NULL){
        return redirect('home'); //awalnya dulu dashboard
    }else{
        return view('login');
    }
});
Route::get('/login', function () {
    return view('login');
});


Route::post('/actionLogin','LoginController@index');
Route::get('/logout','LoginController@logout');
Route::get('/home', 'DashboardController@index')->name('home')->middleware(['token_all']);
Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');
Route::get('/dashboard/getData/{type}','DashboardController@getData');

Route::middleware(['token_all'])->prefix('administrator')->namespace('Administrator')->as('administrator.')->group(function (){
//Route::prefix('administrator')->namespace('Administrator')->as('administrator.')->group(function (){

    /* Route User*/
    Route::resource('users', 'UsersController',['except'=>'show']);
    Route::post('users/getData','UsersController@getData')->name('users.getData');
    Route::get('users/updateStatus/{id}','UsersController@updateStatus')->name('users.updateStatus');
    Route::get('users/detailUser/{id}','UsersController@detailUser')->name('users.detailUser');
    Route::post('users/updateUser','UsersController@updateUser');
    Route::get('users/destroy/{id}', 'UsersController@destroy');
    /* /.Route User */

    /* Route Vendor */
    Route::resource('vendors', 'VendorsController');
    Route::get('vendors/{id}/edit', 'VendorsController@edit');
    Route::put('vendors/update/{id}', 'VendorsController@update');
    Route::get('vendors/destroy/{id}', 'VendorsController@destroy');
    Route::get('vendors/viewVendor/{id}', 'VendorsController@viewVendor');
    /* /.Route Vendor */

    Route::resource('groups', 'GroupsController');
    Route::post('groups/getData','GroupsController@getData')->name('groups.getData');
    Route::post('groups/saveSurveyGroup','GroupsController@saveSurveyGroup');
    Route::get('groups/saveAction/{id}','GroupsController@saveAction');
    Route::get('groups/editGroupAccess/{id}','GroupsController@editGroupAccess');
    Route::get('groups/editFAGroup/{id}','GroupsController@editFAGroup');
    Route::get('groups/deleteFAGroup/{id}','GroupsController@destroy');
    Route::get('groups/editSurveyGroup/{id}','GroupsController@editSurveyGroup');
    Route::post('groups/savemodalEditFAGroup','GroupsController@savemodalEditFAGroup');
    Route::post('groups/savemodalEditSurveyGroup','GroupsController@savemodalEditSurveyGroup');


    Route::resource('skillFA', 'SkillFAController');
    Route::get('skillFA/listFa/{id}', 'SkillFAController@listFa');
    Route::post('skillFA/getData','SkillFAController@getData')->name('skillFA.getData');
    Route::post('skillFA/detailFASkill/{id}','SkillFAController@detailFASkill');
    Route::post('skillFA/detailFaType/{id}','SkillFAController@detailFaType');
    Route::post('skillFA/updateFASkill','SkillFAController@updateFASkill');
    Route::post('skillFA/saveFAType','SkillFAController@saveFAType');
    Route::get('skillFA/destroy/{id}', 'SkillFAController@destroy');


    Route::resource('skillWO', 'SkillWOController');
    Route::post('skillWO/store', 'SkillWOController@store')->name('skillWO.store');
    Route::post('skillWO/getData','SkillWOController@getData')->name('skillWO.getData');
    Route::get('skillWO/destroy/{id}', 'SkillWOController@destroy');
    Route::post('skillWO/detailWoType/{id}', 'SkillWOController@detailWoType');
    Route::post('skillWO/detailWOSkill/{id}','SkillWOController@detailWOSkill');
    Route::post('skillWO/updateWOSkill', 'SkillWOController@updateWOSkill');
    Route::post('skillWO/saveWOType','SkillWOController@saveWOType');

    Route::resource('workerLogin', 'WorkerLoginController');
    Route::resource('hhManagement', 'HHManagementController');
    Route::post('hhManagement/add', 'HHManagementController@store')->name('hhManagement.store');
    Route::post('hhManagement/getData','HHManagementController@getData')->name('hhManagement.getData');
    Route::get('hhManagement/{id}/edit', 'HHManagementController@edit');
    Route::put('hhManagement/update/{id}', 'HHManagementController@update');
    Route::get('hhManagement/destroy/{id}', 'HHManagementController@destroy');

    Route::resource('survey', 'SurveyController');
    Route::get('survey/getTypeData/{id}', 'SurveyController@getTypeData')->name('survey.getTypeData');
    Route::get('survey/updateStatus/{id}','SurveyController@updateStatus')->name('survey.updateStatus');
    Route::get('survey/detailSurvey/{id}','SurveyController@detailSurvey')->name('survey.detailSurvey');
    Route::get('survey/deleteDetail/{id}','SurveyController@deleteDetail')->name('survey.deleteDetail');
    Route::post('survey/updateSurvey','SurveyController@updateSurvey');
    Route::get('survey/destroy/{id}', 'SurveyController@destroy');



    Route::get('mappingFAType/view_character/{id}','MappingFATypeController@view_character')->name('mappingFAType.view_character');
    Route::get('mappingFAType/viewBOM/{id}','MappingFATypeController@viewBOM')->name('mappingFAType.viewBOM');
    Route::get('mappingFAType/viewSeqChar/{id}','MappingFATypeController@viewSeqChar')->name('mappingFAType.viewSeqChar');
    Route::get('mappingFAType/saveUrgent/{id}','MappingFATypeController@saveUrgent')->name('mappingFAType.saveUrgent');
    Route::get('mappingFAType/saveLockFA/{id}','MappingFATypeController@saveLockFA')->name('mappingFAType.saveLockFA');
    Route::get('mappingFAType/savePriority/{id}','MappingFATypeController@savePriority')->name('mappingFAType.savePriority');
    Route::get('mappingFAType/getCode/{id}','MappingFATypeController@getCode');
    Route::get('mappingFAType/viewCode/','MappingFATypeController@viewCode');
    Route::get('mappingFAType/edit/{id}','MappingFATypeController@edit');
    Route::get('mappingFAType/editSeqChar/{id}','MappingFATypeController@editSeqChar');
    Route::post('mappingFAType/updateCharSeq/{id}', 'MappingFATypeController@updateCharSeq');


    Route::resource('areaSurvey', 'AreaSurveyController');
    Route::resource('mappingFAType', 'MappingFATypeController');

    Route::resource('mappingWOTask', 'MappingWOTaskController');
    Route::get('mappingWOTask/view_character/{id}','MappingWOTaskController@view_character')->name('mappingWOTask.view_character');
    Route::get('mappingWOTask/savePriority/{id}','MappingWOTaskController@savePriority')->name('mappingWOTask.savePriority');
    Route::get('mappingWOTask/saveUrgent/{id}','MappingWOTaskController@saveUrgent')->name('mappingWOTask.saveUrgent');
    Route::get('mappingWOTask/saveLockWO/{id}','MappingWOTaskController@saveLockWO')->name('mappingWOTask.saveLockWO');
    Route::get('mappingWOTask/viewBOM/{id}','MappingWOTaskController@viewBOM');
    Route::get('mappingWOTask/getCode/{id}','MappingWOTaskController@getCode');
    Route::get('mappingWOTask/edit/{id}','MappingWOTaskController@edit');

    Route::resource('systemParameter', 'SystemParameterController');
    Route::get('getDataModule','UsersController@getDataModule')->name('users.getDataModule');
    Route::get('getDetailModule','UsersController@getDetailModule')->name('users.getDetailModule');



    Route::post('skillWO/getData','SkillWOController@getData')->name('skillWO.getData');
    Route::post('vendors/getData','VendorsController@getData')->name('vendors.getData');
    Route::post('workerLogin/getData','WorkerLoginController@getData')->name('workerLogin.getData');
    Route::get('workerLogin/editSurvey/{id}','WorkerLoginController@editSurvey');
    Route::post('workerLogin/updateListSurvey/{id}','WorkerLoginController@updateListSurvey');
    Route::get('workerLogin/editDispatch/{id}','WorkerLoginController@editDispatch');
    Route::post('workerLogin/updateListFA/{id}','WorkerLoginController@updateListFA');
    Route::get('workerLogin/viewDispatch/{id}','WorkerLoginController@viewDispatch');
    Route::get('workerLogin/viewSkill/{id}','WorkerLoginController@viewSkill');
    Route::get('workerLogin/viewSkillWO/{id}','WorkerLoginController@viewSkillWO');
    Route::get('workerLogin/viewSurvey/{id}','WorkerLoginController@viewSurvey');
    Route::get('workerLogin/editPasword/{user_id}', 'WorkerLoginController@editPassword');
    Route::post('workerLogin/updatePassword/{id}', 'WorkerLoginController@updatePassword');
    Route::get('workerLogin/destroy/{id}', 'WorkerLoginController@destroy');
    Route::get('workerLogin/workerWO/{type}','WorkerLoginController@workerWO');

    Route::post('survey/getData','SurveyController@getData')->name('survey.getData');
    Route::post('areaSurvey/getData','AreaSurveyController@getData')->name('areaSurvey.getData');
    Route::post('mappingFAType/getData','MappingFATypeController@getData')->name('mappingFAType.getData');
    Route::post('mappingWOTask/getData','MappingWOTaskController@getData')->name('mappingWOTask.getData');
    Route::post('systemParameter/getData','SystemParameterController@getData')->name('systemParameter.getData');
});



Route::middleware(['token_all'])->prefix('transaction')->namespace('Transaction')->as('transaction.')->group(function (){

    Route::resource('messaging', 'MessagingController');
    Route::get('messaging/compose/{type}','MessagingController@compose');
    Route::get('messaging/status/{type}','MessagingController@draf');
    Route::get('messaging/destroy/{type}','MessagingController@destroy');
    Route::get('messaging/detail/{type}','MessagingController@detail');
    Route::get('messaging/edit/{type}','MessagingController@edit');

app/Models/Administrator/Access_modules.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class Access_modules extends Model
{
    //
}

app/Models/Administrator/Admin.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;
use App\Models\Administrator\Admin;
use App\Models\Administrator\Groups;


class Admin extends Model
{
    //

    protected $table = 'admin';


    public function users()
    {
    	return $this->hasOne(Users::class,'id');
    }

   
}

app/Models/Administrator/FA_Group.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class FA_Group extends Model
{
    //
    protected $table = 'dispatch_group_master';
}

app/Models/Administrator/FA_Group_Access.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class FA_Group_Access extends Model
{
    //
    protected $table = 'fa_group_access';
}

app/Models/Administrator/FA_alg_validation.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class FA_alg_validation extends Model
{
    protected $table = 'fa_alg_validation';
}

app/Models/Administrator/FA_char_type.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class FA_char_type extends Model
{
    protected $table = 'fa_char_type';
    public function fa_char_value()
    {
        return $this->belongsTo(FA_char_value::class,'char_type_cd','char_type_cd');
    }

    public function fa_alg_validation()
    {
        return $this->belongsTo(FA_alg_validation::class,'alg_cd','adhoc_val_alg_cd');
    }
}

app/Models/Administrator/FA_char_value.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class FA_char_value extends Model
{
    protected $table = 'fa_char_value';
}

app/Models/Administrator/FA_mapping.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;
use App\Models\Transaction\FA_transaction;


class FA_mapping extends Model
{
    //
    protected $table = 'fa_mapping';

     public function fa_transaction()
    {
    	return $this->belongsTo(FA_transaction::class);
    }
}

app/Models/Administrator/FA_mapping_char_type.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class FA_mapping_char_type extends Model
{
    protected $table = 'fa_mapping_char_type';
    public function fa_char_type()
    {
        return $this->belongsTo(FA_char_type::class,'char_type_cd','char_type_cd');
    }

    public function fa_type()
    {
        return $this->belongsTo(Fa_type::class,'fa_type_cd','fa_type_cd');
    }
}

app/Models/Administrator/FA_type_lang.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class FA_type_lang extends Model
{
    protected $table = 'fa_type_lang';
}

app/Models/Administrator/Fa_type.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;
use App\Models\Transaction\FA_transaction;

class Fa_type extends Model
{
    //

    protected $table = 'fa_type';

    public function fa_transaction()
    {
    	return $this->belongsTo(FA_transaction::class);
    }

    public function fa_type_lang()
    {
        return $this->hasOne(FA_type_lang::class,'fa_type_cd','id');
    }

}

app/Models/Administrator/Groups.php
<?php

namespace App\Models\Administrator;
use Illuminate\Database\Eloquent\Model;
use App\Models\Administrator\Users;

class Groups extends Model
{
    
    protected $table = 'group_access';

    public static function boot() {
        parent::boot();

        static::deleting(function($groups) { 
            $groups->survey_group_access()->delete();
            $groups->fa_group_access()->delete(); 
        });
    }

    public function users()
    {
    	return $this->hasOne(Users::class);
    }

    public function fa_group_access()
    {
        return $this->hasMany(FA_Group_Access::class,'group_access_id','id');
    }

    public function survey_group_access()
    {
        return $this->hasMany(Survey_group_access::class,'group_access_id','id');
    }
}

app/Models/Administrator/HHManagement.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class HHManagement extends Model
{
    protected $table = 'hh_management';
}

app/Models/Administrator/Log_fa_status.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class Log_fa_status extends Model
{
    //
    protected $table = 'log_fa_status';
}

app/Models/Administrator/Log_wo_status.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class Log_wo_status extends Model
{
    protected $table = 'log_wo_status';
}

app/Models/Administrator/Modules.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use App\Models\User;


class Modules extends Model
{
    //

    public function getModule()
    {
    	// return DB::table('modules')->get();

    	        return $this->hasOne(User::class);
    	     ///  echo 'tes';

    }
}

app/Models/Administrator/Skill_fa.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class Skill_fa extends Model
{
    //
    protected $table = 'skill_fa';

    public function worker()
    {
    	return $this->hasOne(Workers::class,'worker_id');
    }

    public function skill_fa_detail()
    {
        return $this->hasMany(Skill_fa_detail::class,'skill_fa_id');
    }


}

app/Models/Administrator/Skill_fa_detail.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class Skill_fa_detail extends Model
{
    //
    protected $table = 'skill_fa_detail';

    public function skill_fa()
    {
        return $this->belongsTo(Skill_fa::class,'skill_fa_id');
    }

    public function fa_type()
    {
        return $this->belongsTo(Fa_type::class);
    }


}

app/Models/Administrator/Skill_wo.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class Skill_wo extends Model
{
    //protected table
    protected $table = 'skill_wo';

    public function worker()
    {
    	return $this->hasOne(Workers::class,'worker_id');
    }

    public function skill_wo_detail()
    {
        return $this->hasMany(Skill_wo_detail::class,'skill_wo_id');
    }
}

app/Models/Administrator/Skill_wo_detail.php
<?php

namespace App\Models\Administrator;

use Illuminate\Database\Eloquent\Model;

class Skill_wo_detail extends Model
{
    //protected
    protected $table = 'skill_wo_detail';

    public function skill_wo()
    {
        return $this->belongsTo(Skill_wo::class,'skill_wo_id');
    }

    public function wo_task()
    {
        return $this->belongsTo(Wo_task::class,'job_code_id');
    }
}

resources/views/administrator/skillWO/js_skillWO.blade.php
<script type="text/javascript">
var baris = 0;
$( document ).ready(function() {
    //for datatable 
  $('#tableSkillWO').dataTable({ });
});
/*
function addRowSkillWO()
{
    baris++;
    var _div = $('#formSkillWO');
    _div.append('<div class="form-group row rowSkillWO_'+baris+'">'+
                  '<label for="" class="col-sm-3 col-form-label"></label>'+
                  '<div class="col-sm-8">'+
                      '<select class="form-control" name="skillWOType">'+
                          '<option>Skill WO</option>'+
                          '<option>Skill WO</option>'+
                          '<option>Skill WO</option>'+
                        '</select>'+
                  '</div>'+
                  '<div class="col-sm-1"  style="margin-top:7px;">'+
                    '<a href="javascript:void(0)" onclick="deleteRowSkillWO()" style="color:red"> <i class="fa fa-minus"></i> </a>'+
                  '</div>'+
                '</div>');
    

}

function deleteRowSkillWO()
{   
    $('.rowSkillWO_'+baris+'').remove();
    baris--;
}

function modalSkillWO()
{
      var body = '<div class="alert alert-danger" id="error-alert" style="display: none"></div>'+
              '<form id="formSkillWO">'+
              '<input type="hidden" name="_token" value="{{csrf_token()}}">'+
               '<div class="form-group row">'+
                  '<label  class="col-sm-3 col-form-label">Group Skill Name</label>'+
                  '<div class="col-sm-8">'+
                    '<input type="text" name="skill_wo_name" class="form-control" placeholder="Group Skill Name">'+
                  '</div>'+
                  '<div class="col-sm-1"  style="margin-top:7px;">'+
                    '<a href="javascript:void(0)" onclick="modalWOType()"> <i class="fa fa-edit"></i> </a>'+
                  '</div>'+
                '</div>'+
          '</form>';
        var footer = '<button type="button" class="btn btn-secondary  btnFooterModal" data-dismiss="modal"onclick="window.location.reload()">Cancel</button>'+
        '<button type="button" class="btn btn-primary  btnFooterModal" onclick="saveWO()">Save</button>';
    hidden_error();

    $('#modalSkillWO').find('.modal-title').text('Add New Group WO Skill');
    $('#modalSkillWO').find('.modal-footer').html(footer);
    $('#modalSkillWO').find('.modal-body').html(body);
    $('#modalSkillWO').modal('show');   


}*/

function modalWOType(){
    $('#modalWOType').modal('show');
}

function ambilSemua(resp){
  if (resp.checked)
  {
     $('.rowWoType').prop('checked', resp.checked);
  }
  else
  {
    $('.rowWoType').prop('checked', resp.checked);
  }
}

function closeModal()
{
    $('#modalWOType').modal('hide');
}

function saveWO(){
    console.log('processing');
    var data = $('#formSkillWO').serialize();
    $.ajax({
        url:"{{route('administrator.skillWO.store')}}",
        //data:{'skill_wo_name':$('[name="skill_wo_name"]').val(),'detail_value':localStorage.getItem('join_val')},
        data:$('form#formSkillWO, form#formwoTask').serialize(),
        dataType:'JSON',
        type:'POST',
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        },
        success:function(data){
            if(data.errors)
            {
                $('.alert-danger').show();
                $('.alert-danger').empty();
                $.each(data.errors,function(key,value){
                    $('.alert-danger').append('<li>'+value+'</li>');
                })
            }
            else
            {
                swal('Success','Group has been saved successfully!','success');
                location.reload();
            }
            hidden_error();
        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    })
}

function detailSkillWO(id,action){
    var body;
    var footer;
     $.ajax({
        url:"skillWO/detailWOSkill/"+id,
        data:{'action':action},
        //dataType:'JSON',
        type:'POST',
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        },
        success:function(data){
             body ='<div class="alert alert-danger" id="error-alert" style="display: none"></div>';
             body += data;
             if(action == 'detail')
             {
                footer = '<button type="button" class="btn btn-secondary  btnFooterModal" data-dismiss="modal" onclick="window.location.reload()">Cancel</button>';   
                var title = 'Detail Group Skill WO';
             }
             else if(action == 'edit')
             {
                footer = '<button type="button" class="btn btn-secondary  btnFooterModal" data-dismiss="modal" onclick="window.location.reload()">Cancel</button>'+
                    '<button type="button" class="btn btn-secondary  btnFooterModal" onclick="updateWOSkill()">Update</button>';   
                title = 'Edit Group Skill WO';
             }

             

             $('#modalSkillWO').find('.modal-title').text(title);
             $('#modalSkillWO').find('.modal-body').html(body);
             $('#modalSkillWO').find('.modal-footer').html(footer);
             $('#modalSkillWO').modal('show');

        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    });
}

function detailWoType(id,action)
{
    var body;
    var footer;
     $.ajax({
        url:"skillWO/detailWoType/"+id,
        data:{'page':'detail'},
        type:'POST',
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        },
        success:function(data){
             body = data;

              if(action == 'detail')
             {
                footer = '<button type="button" class="btn btn-secondary  btnFooterModal" data-dismiss="modal" onclick="">Cancel</button>';   
             }
             else
             {
                footer = '<button type="button" class="btn btn-secondary  btnFooterModal" data-dismiss="modal" onclick="closeModal()">Cancel</button>'+
                    '<button type="button" class="btn btn-secondary  btnFooterModal" onclick="saveWOType()">Update</button>';   
             }
             $('[name="skill_wo_id"]').val(id);
             $('#modalWOType').find('tbody').html(body);
             $('#modalWOType').find('.modal-footer').html(footer);
             $('#modalWOType').modal('show');
        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    })
}

function updateWOSkill(){
    $.ajax({
        url:"skillWO/updateWOSkill",
        data:{'skill_wo_name':$('[name="skill_wo_name"]').val(),'wo_id':$('[name="wo_id"]').val(),'detail_value':localStorage.getItem('join_val')},
        dataType:'JSON',
        type:'POST',
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        },
        success:function(data){
            if(data.errors)
            {
                $('.alert-danger').show();
                $('.alert-danger').empty();
                $.each(data.errors,function(key,value){
                    $('.alert-danger').append('<li>'+value+'</li>');
                })
            }
            else
            {
                swal('Success','Group has been saved successfully!','success');
                location.reload();
            }
            hidden_error();
        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    });
}

function saveWOType()
{
    localStorage.clear();
    var checkedValues = $('input:checkbox:checked').map(function() {
        return this.value;
    }).get();

    var join_val = checkedValues.join(',');

    localStorage.setItem('join_val',join_val);

     $.ajax({
        url:"skillWO/saveWOType",
        data:{'detail_value':localStorage.getItem('join_val'),'skill_wo_id':$('[name="skill_wo_id"]').val()},
        dataType:'JSON',
        type:'POST',
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        },
        success:function(data){
         
                $('#modalWOType').modal('hide');

        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    })

}

function deleteSkillWO(id){
    console.log('Delete processing');
    
    swal({
      title: "Apakah Data Ingin Di Hapus?",
      text: "Jika Data Sudah Di Hapus, Tidak Dapat Di Kembalikan",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "Hapus",
      closeOnConfirm: false
    }, function(isConfirm){
        if (!isConfirm) return;
        $.ajax({
            url:'skillWO/destroy/'+id,
            data:id,
            dataType:'JSON',
            type:'GET',
            success:function(data){
                swal("Berhasil!", "Skill WO berhasil di hapus", "success");
                location.reload();
            },
              error: function (xhr, ajaxOptions, thrownError) {
                    swal("Gagal!", "Skill WO gagal di hapus", "error");
              }
        });
    });
}
</script>

resources/views/administrator/skillWO/v_detail_skill_wo.blade.php
  <form id="formSkillWO">
      <input type="hidden" name="_token" value="{{csrf_token()}}">
       <div class="form-group row">
          <label  class="col-sm-3 col-form-label">Group Skill Name</label>
          <div class="col-sm-8">
            <input type="hidden" name="wo_id" value="{{$skill_wo->id}}">
            <input type="text" name="skill_wo_name" class="form-control" value="{{$skill_wo->skill_wo_name}}" placeholder="Group Skill Name">
          </div>
          <div class="col-sm-1"  style="margin-top:7px;">
            <a href="javascript:void(0)" onclick="detailWoType('{{$skill_wo->id}}','{{$action}}')"> <i class="fa fa-edit"></i> </a>
          </div>
        </div>
  </form><!-- /form -->

resources/views/administrator/skillWO/v_detail_wo_type.blade.php
@php
	use App\Models\Administrator\Skill_wo_detail;
@endphp

@foreach($wo_type as $wo)
      @php $dt = Skill_wo_detail::where('job_code_id',$wo->id)->where('skill_wo_id',$id)->first(); @endphp

      <tr>
        <td>
        	<input type="checkbox" name="wo_task" 
        	<?php 
        		$ck = '';
        		if(!empty($dt) && ($wo->id==$dt->job_code_id)):
        			$ck = 'checked';
        	   endif;
          ?>
         <?= $ck ?> class="rowWoType" value="{{$wo->id}}"></td>
        <td>{{$wo->job_code}}</td>
      </tr>
@endforeach