routes/web.php
    Route::get('mappingFAType/viewCode/','MappingFATypeController@viewCode');
    Route::get('mappingFAType/edit/{id}','MappingFATypeController@edit');
    Route::get('mappingFAType/editSeqChar/{id}','MappingFATypeController@editSeqChar');
    Route::post('mappingFAType/updateCharSeq/{id}', 'MappingFATypeController@updateCharSeq');


    Route::resource('areaSurvey', 'AreaSurveyController');
    Route::resource('mappingFAType', 'MappingFATypeController');

    Route::resource('mappingWOTask', 'MappingWOTaskController');
    Route::get('mappingWOTask/view_character/{id}','MappingWOTaskController@view_character')->name('mappingWOTask.view_character');
    Route::get('mappingWOTask/savePriority/{id}','MappingWOTaskController@savePriority')->name('mappingWOTask.savePriority');
    Route::get('mappingWOTask/saveUrgent/{id}','MappingWOTaskController@saveUrgent')->name('mappingWOTask.saveUrgent');
    Route::get('mappingWOTask/saveLockWO/{id}','MappingWOTaskController@saveLockWO')->name('mappingWOTask.saveLockWO');
    Route::get('mappingWOTask/viewBOM/{id}','MappingWOTaskController@viewBOM');
    Route::get('mappingWOTask/getCode/{id}','MappingWOTaskController@getCode');
    Route::get('mappingWOTask/edit/{id}','MappingWOTaskController@edit');

    Route::resource('systemParameter', 'SystemParameterController');
    Route::get('getDataModule','UsersController@getDataModule')->name('users.getDataModule');
    Route::get('getDetailModule','UsersController@getDetailModule')->name('users.getDetailModule');



    Route::post('skillWO/getData','SkillWOController@getData')->name('skillWO.getData');
    Route::post('vendors/getData','VendorsController@getData')->name('vendors.getData');
    Route::post('workerLogin/getData','WorkerLoginController@getData')->name('workerLogin.getData');
    Route::get('workerLogin/editSurvey/{id}','WorkerLoginController@editSurvey');
    Route::post('workerLogin/updateListSurvey/{id}','WorkerLoginController@updateListSurvey');
    Route::get('workerLogin/editDispatch/{id}','WorkerLoginController@editDispatch');
    Route::post('workerLogin/updateListFA/{id}','WorkerLoginController@updateListFA');
    Route::get('workerLogin/viewDispatch/{id}','WorkerLoginController@viewDispatch');
    Route::get('workerLogin/viewSkill/{id}','WorkerLoginController@viewSkill');
    Route::get('workerLogin/viewSkillWO/{id}','WorkerLoginController@viewSkillWO');
    Route::get('workerLogin/viewSurvey/{id}','WorkerLoginController@viewSurvey');
    Route::get('workerLogin/editPasword/{user_id}', 'WorkerLoginController@editPassword');
    Route::post('workerLogin/updatePassword/{id}', 'WorkerLoginController@updatePassword');
    Route::get('workerLogin/destroy/{id}', 'WorkerLoginController@destroy');
    Route::get('workerLogin/workerWO/{type}','WorkerLoginController@workerWO');

    Route::post('survey/getData','SurveyController@getData')->name('survey.getData');
    Route::post('areaSurvey/getData','AreaSurveyController@getData')->name('areaSurvey.getData');
    Route::post('mappingFAType/getData','MappingFATypeController@getData')->name('mappingFAType.getData');
    Route::post('mappingWOTask/getData','MappingWOTaskController@getData')->name('mappingWOTask.getData');
    Route::post('systemParameter/getData','SystemParameterController@getData')->name('systemParameter.getData');
});



Route::middleware(['token_all'])->prefix('transaction')->namespace('Transaction')->as('transaction.')->group(function (){

    Route::resource('messaging', 'MessagingController');
    Route::get('messaging/compose/{type}','MessagingController@compose');
    Route::get('messaging/status/{type}','MessagingController@draf');
    Route::get('messaging/destroy/{type}','MessagingController@destroy');
    Route::get('messaging/detail/{type}','MessagingController@detail');
    Route::get('messaging/edit/{type}','MessagingController@edit');
    Route::get('messaging/update/{type}','MessagingController@update');

    Route::resource('assignmentFA', 'AssignmentFAController');
    Route::post('assignmentFA/getDataByFilter','AssignmentFAController@getDataByFilter')->name('assignmentFA.getDataByFilter');
    Route::post('assignmentFA/import','AssignmentFAController@import')->name('import');
    Route::post('assignmentFA/multiSaveWorker','AssignmentFAController@multiSaveWorker');
    Route::get('assignmentFA/getWorker/{id}','AssignmentFAController@getWorker')->name('assignmentFA.getWorker');
    Route::get('assignmentFA/saveWorker/{id}','AssignmentFAController@saveWorker')->name('survey.saveWorker');
    Route::get('assignmentFA/saveAssignDate/{id}','AssignmentFAController@saveAssignDate')->name('survey.saveAssignDate');
    Route::get('assignmentFA/saveReAssignedDate/{id}','AssignmentFAController@saveReAssignedDate')->name('survey.saveReAssignedDate');
    Route::get('assignmentFA/getWorkerOne/{id}','AssignmentFAController@getWorkerOne')->name('survey.getWorkerOne');
    Route::get('assignmentFA/saveUrgent/{id}','AssignmentFAController@saveUrgent')->name('survey.saveUrgent');
    Route::get('assignmentFA/savePriority/{id}','AssignmentFAController@savePriority')->name('survey.savePriority');
    Route::get('assignmentFA/export/{type}','AssignmentFAController@export');
	Route::get('assignmentFA/getData/{type}','AssignmentFAController@getData');
	Route::get('assignmentFA/search/{type}','AssignmentFAController@search');
    Route::get('assignmentFA/filterAssignmentFA/{type}','AssignmentFAController@filterAssignmentFA');
    Route::post('assignmentFA/refresh','AssignmentFAController@refresh_all_fa');
    Route::get('assignmentFA/detailNomen/{id}','AssignmentFAController@detailNomen');

    Route::resource('assignmentWO', 'AssignmentWOController');
    Route::post('assignmentWO/refresh','AssignmentWOController@refresh');
    Route::get('assignmentWO/getData/{type}','AssignmentWOController@getData');
    Route::get('assignmentWO/saveUrgent/{id}','AssignmentWOController@saveUrgent');
    Route::get('assignmentWO/savePriority/{id}','AssignmentWOController@savePriority');
    Route::get('assignmentWO/saveWorker/{id}','AssignmentWOController@saveWorker');
    Route::post('assignmentWO/import','AssignmentWOController@import')->name('importWO');
    Route::get('assignmentWO/export/{type}','AssignmentWOController@export');
    Route::get('assignmentWO/saveAssignDate/{id}','AssignmentWOController@saveAssignDate');
    Route::get('assignmentWO/search/{type}','AssignmentWOController@search');
    Route::get('assignmentWO/filterAssignmentWO/{type}','AssignmentWOController@filterAssignmentWO');

    Route::resource('assignmentSurvey', 'AssignmentSurveyController');
    Route::post('assignmentSurvey/getData','AssignmentSurveyController@getData')->name('assignmentSurvey.getData');
    Route::get('assignmentSurvey/json-pc/{id}','AssignmentSurveyController@pc'); 
    Route::get('assignmentSurvey/json-ez/{id}','AssignmentSurveyController@ez'); 
    Route::get('assignmentSurvey/json-bk/{id}','AssignmentSurveyController@bk'); 
    Route::get('assignmentSurvey/json-worker/{id}','AssignmentSurveyController@selectWorker'); 
    Route::get('assignmentSurvey/viewAB/{id}','AssignmentSurveyController@viewAB');
    Route::get('assignmentSurvey/viewPC/{id}','AssignmentSurveyController@viewPC');

});


Route::middleware(['token_all'])->prefix('monitoring')->namespace('Monitoring')->as('monitoring.')->group(function (){
    Route::resource('monitoringFA', 'MonitoringFAController');
	Route::get('monitoringFA/getData/{type}','MonitoringFAController@getData');
	Route::get('monitoringFA/search/{type}','MonitoringFAController@search');
    Route::get('monitoringFA/detailNomen/{id}','MonitoringFAController@detailNomen');
    Route::post('monitoringFA/getDataBydate','MonitoringFAController@getDataBydate')->name('monitoringFA.getDataBydate');
    Route::post('monitoringFA/getDetail/{id}','MonitoringFAController@getDetail');
    Route::post('monitoringFA/getCharacteristic/{id}','MonitoringFAController@getCharacteristic');
    Route::post('monitoringFA/getMaterialUsage/{id}','MonitoringFAController@getMaterialUsage');
    Route::post('monitoringFA/getTTD/{id}','MonitoringFAController@getTTD');
    Route::get('monitoringFA/getphotofa/{id}', 'MonitoringFAController@getphotofa');
    Route::get('monitoringFA/downloadPdf/{id}', 'MonitoringFAController@downloadPdf');
    Route::post('monitoringFA/updateCharacteristic/{id}', 'MonitoringFAController@updateCharacteristic');
    Route::get('monitoringFA/editCharacteristicById/{id}', 'MonitoringFAController@editCharacteristicById');
    Route::get('monitoringFA/getCharWms/{id}', 'MonitoringFAController@sendBackToSimpel');
    Route::get('monitoringFA/getComp/{id}', 'MonitoringFAController@sendCompBackToSimpel');
    Route::get('monitoringFA/get_history/{id}', 'MonitoringFAController@get_history');
    Route::get('monitoringFA/filterMonitoringFA/{type}','MonitoringFAController@filterMonitoringFA');

    Route::resource('monitoringWO', 'MonitoringWOController');
    Route::post('monitoringWO/getData','MonitoringWOController@getData')->name('monitoringWO.getData');
    Route::post('monitoringWO/getDetail/{id}/{no_wo_task}','MonitoringWOController@getDetail');
    Route::post('monitoringWO/getDataBydate','MonitoringWOController@getDataBydate')->name('monitoringWO.getDataBydate');
    Route::get('monitoringWO/downloadPdf/{id}', 'MonitoringWOController@downloadPdf');
    Route::get('monitoringWO/search/{type}','MonitoringWOController@search');
    Route::get('monitoringWO/getData/{type}','MonitoringWOController@getData');
    Route::get('monitoringWO/filterMonitoringWO/{type}','MonitoringWOController@filterMonitoringWO');
    Route::get('monitoringWO/getCharacteristic/{id}/{no_wo_task}', 'MonitoringWOController@getCharacteristic');
    Route::get('monitoringWO/getMaterialUsage/{id}/{no_wo_task}', 'MonitoringWOController@getMaterialUsage');
    Route::get('monitoringWO/getTTD/{id}/{no_wo_task}', 'MonitoringWOController@getTTD');

app/Models/Transaction/AssignmentSurvey.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;
use App\Models\Administrator\Survey;
use App\Models\Administrator\Workers;


class AssignmentSurvey extends Model
{

    protected $table = 'survey_transaction';

    public function survey()
    {
    	return $this->belongsTo(Survey::class,'survey_id','id');
    }

    public function worker()
    {
        return $this->belongsTo(Workers::class,'worker_id','id');
    }
}

app/Models/Transaction/Code_AB.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Code_AB extends Model
{
    //protected table
    protected $table = 'code_ab';     
}

app/Models/Transaction/Code_BK.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Code_BK extends Model
{
    protected $table = 'code_bk';
}

app/Models/Transaction/Code_EZ.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Code_EZ extends Model
{
    protected $table = 'code_ez';
}

app/Models/Transaction/Code_PC.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Code_PC extends Model
{
    protected $table = 'code_pc';
}

app/Models/Transaction/Customer.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    //

    protected $table = 'customer';

    public function fa_transaction()
    {
    	return $this->belongsTo(FA_transaction::class);
    }
}

app/Models/Transaction/FA_Template_BOM.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class FA_Template_BOM extends Model
{
    protected $table = 'fa_template_BOM';
    public function fa_template_BOM_detail()
    {
        return $this->hasMany(FA_Template_BOM_detail::class,'fa_template_BOM_id');
    }
}

app/Models/Transaction/FA_Template_BOM_Characteristic.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class FA_Template_BOM_Characteristic extends Model
{
    protected $table = 'fa_template_bom_characteristic';
}

app/Models/Transaction/FA_Template_BOM_code.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class FA_Template_BOM_code extends Model
{
    protected $table = 'fa_template_BOM_code';
    protected $primaryKey = 'id';
    protected $fillable = ['code', 'name', 'category', 'unit_of_purch'];
    protected $guarded = [];
}

app/Models/Transaction/FA_Template_BOM_detail.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class FA_Template_BOM_detail extends Model
{
    protected $table = 'fa_template_BOM_detail';
}

app/Models/Transaction/FA_Transaction_characteristic.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class FA_Transaction_characteristic extends Model
{
    protected $table = 'fa_transaction_characteristic';
    protected $fillable = ['user_id', 'fa_transaction_id', 'fa_type_cd', 'name_characteristic', 'value_characteristic','sequence','char_type_cd','char_type_flg', 'created_by', 'updated_by'];

    public function transaction(){
        return $this->belongsTo(FA_transaction::class,'fa_transaction_id','fa_transaction_id');
    }
}

app/Models/Transaction/FA_Transaction_material_usage.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class FA_Transaction_material_usage extends Model
{
    protected $table = 'fa_transaction_material_usage';

    public function transaction(){
        return $this->belongsTo(FA_transaction::class,'fa_transaction_id','fa_transaction_id');
    }
}

app/Models/Transaction/FA_Transaction_photo.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class FA_Transaction_photo extends Model
{
    protected $table = 'fa_transaction_photo';

    public function transaction(){
        return $this->belongsTo(FA_transaction::class,'fa_transaction_id','fa_transaction_id');
    }
}

app/Models/Transaction/FA_Transaction_ttd.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class FA_Transaction_ttd extends Model
{
    protected $table = 'fa_transaction_ttd';

    public function transaction(){
        return $this->belongsTo(FA_transaction::class,'fa_transaction_id','fa_transaction_id');
    }
}

app/Models/Transaction/FA_transaction.php
<?php

namespace App\Models\Transaction;

use App\Models\Administrator\Users;
use App\Models\Administrator\Workers;
use Illuminate\Database\Eloquent\Model;
use App\Models\Administrator\FA_type;
use App\Models\Administrator\FA_mapping;



class FA_transaction extends Model
{
    //

    protected $table = 'fa_transaction';
    protected $fillable = ['created_at'];

 	public function customer()
 	{
 		//return $this->hasOne(Customer::class,'nomen','nomen');
 		return $this->hasOne(Customer::class,'fa_transaction_id','fa_transaction_id');
 	}

 	public function fa_type()
 	{
 		return $this->hasOne(FA_type::class,'fa_type_cd','fa_type_cd');
 	}

 	public function fa_mapping()
 	{
 		return $this->hasOne(FA_mapping::class,'fa_type_cd','fa_type_cd');
 	}

 	public function worker()
    {
        return $this->belongsTo(Workers::class,'worker_id','id');
    }

 	public function fa_template_BOM()
    {
        return $this->belongsTo(FA_Template_BOM::class,'fa_type_cd','fa_type_cd');
    }

    public function fa_transaction_photo()
    {
    	require $this->belongsTo(FA_Transaction_photo::class, 'user_id','user_id');
    }

    public function fa_transaction_ttd()
    {
    	require $this->belongsTo(FA_Transaction_ttd::class, 'user_id','user_id');
    }


}

app/Models/Transaction/Message.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
  protected $table = 'messages';

  public function message_to()
  {
    return $this->hasMany(Message_To::class,'id','id_send');
  }
}

app/Models/Transaction/Message_To.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Message_TO extends Model
{
  protected $table = 'message_to';
}

app/Models/Transaction/Survey_Transaction.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Survey_Transaction extends Model
{
    protected $table = 'survey_transaction';
}

app/Models/Transaction/Survey_Transaction_Characteristic.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Survey_Transaction_Characteristic extends Model
{
    protected $table = 'survey_transaction_characteristic';
    protected $fillable = ['user_id', 'survey_code', 'type_data', 'characteristic_name', 'characteristic_value', 'created_by', 'updated_by'];
}

app/Models/Transaction/Survey_Transaction_Photo.php
<?php

namespace App\Models\Transaction;

use Illuminate\Database\Eloquent\Model;

class Survey_Transaction_Photo extends Model
{
    protected $table = 'survey_transaction_photo';
}

resources/views/transaction/assignmentSurvey/js_assignmentSurvey.blade.php
<script type="text/javascript">
$(document).ready(function() {
    $('#tableAssignmentSurvey').dataTable({
    });
});
function editAssignmentSurvey(id)
{
    var data = $('#formSurveyTransaction').serialize();
  

    $.ajax({
        url:"assignmentSurvey/"+id+"/edit",
        data:'',
       // dataType:'JSON',
        type:'GET',
        success:function(data){
            footer = '<button type="button" class="btn btn-secondary  btnFooterModal" data-dismiss="modal" onclick="window.location.reload()">Close</button>';
            footer += '<button type="button" class="btn btn-secondary  btnFooterModal"  onclick="updateAssignmentSurvey('+id+')">Update</button>';
            $('#modalAssignmentSurvey').find('.modal-footer').html(footer);
            $('#modalAssignmentSurvey').find('.modal-body').html(data);
            $('#modalAssignmentSurvey').modal('show');
            datePicker();
        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    })   
}

function updateAssignmentSurvey(id)
{
     var data = $('#formSurveyTransaction').serialize();
  

    $.ajax({
        url:"assignmentSurvey/"+id+"",
        data:data,
        dataType:'JSON',
        type:'PUT',
        headers: {
          'X-CSRF-TOKEN' : '{{csrf_token()}}',
        },
        success:function(data){
            if(data.errors)
            {
                $('.alert-danger').show();
                $.each(data.errors,function(key,value){
                    $('.alert-danger').append('<li>'+value+'</li>');
                })

            }
            else
            {
                swal('Success','Survey has been saved successfully!','success');
                location.reload();
            }
        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    })   
}

function add_assignment_survey()
{
    var data = $('#formSurveyTransaction').serialize();
  

    $.ajax({
        url:"{{route('transaction.assignmentSurvey.create')}}",
        data:'',
       // dataType:'JSON',
        type:'GET',
        success:function(data){
            $('#modalAssignmentSurvey').find('.modal-body').html(data);
            $('#modalAssignmentSurvey').modal('show');
            datePicker();
        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    })
}

function saveAssignSurvey()
{

    var data = $('#formSurveyTransaction').serialize();
  

    $.ajax({
        url:"{{route('transaction.assignmentSurvey.store')}}",
        data:data,
        dataType:'JSON',
        type:'POST',
        headers: {
          'X-CSRF-TOKEN' : '{{csrf_token()}}',
        },
        success:function(data){
            if(data.errors)
            {
                $('.alert-danger').show();
                $.each(data.errors,function(key,value){
                    $('.alert-danger').append('<li>'+value+'</li>');
                })
                hidden_error();
                datePicker();

            }
            else
            {
                swal('Success','Survey has been saved successfully!','success');
                location.reload();
            }
        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    })
}

function detail_ab(ab_id){
    $.ajax({
        url:"assignmentSurvey/viewAB/"+ab_id,
        data:'kosong',
        // dataType:'JSON',
        type:'GET',
        success:function(data){
            $('#modalViewDetail').find('.modal-header').html('<button type="button" class="close" onclick="closeDetailData()">'+
            '<span aria-hidden="true" style="color:#fff">&times;</span>'+
            '</button>'+
            '<h4 class="modal-title" style="text-align:center"> Detail AB </h4>'
            );
            $('#modalViewDetail').find('.modal-footer').html('<button type="button" class="btn btn-secondary  btnFooterModal" onclick="closeDetailData()">Close</button>')
            $('#modalViewDetail').find('.modal-body').html(data);
            $('#modalViewDetail').modal('show');
        },
          error: function (xhr, ajaxOptions, thrownError) {
                swal("error!", thrownError, "error");
        }
    })
}

function detail_pc(id){
    $.ajax({
        url:"assignmentSurvey/viewPC/"+id,
        data:'kosong',
        type:'GET',
        success:function(data){
            $('#modalViewDetail').find('.modal-header').html('<button type="button" class="close" onclick="closeDetailData()">'+
            '<span aria-hidden="true" style="color:#fff">&times;</span>'+
            '</button>'+
            '<h4 class="modal-title" style="text-align:center"> Detail PC-EZ </h4>'
            );
            $('#modalViewDetail').find('.modal-footer').html('<button type="button" class="btn btn-secondary  btnFooterModal" onclick="closeDetailData()">Close</button>')
            $('#modalViewDetail').find('.modal-body').html(data);
            $('#modalViewDetail').modal('show');
        },
        error:function(xhr, ajaxOptions, thrownError){
            swal("error!", thrownError, "error");
        }
    })
}

function closeDetailData()
{
    $('#modalViewDetail').modal('hide');
}
</script>

resources/views/transaction/assignmentSurvey/v_index_assignmentSurvey.blade.php
@extends('layouts.app')

@section('head')
    Transaction | Assignment Survey
@endsection

@section('title')
    <i class="fa fa-home"></i> Transaction  | <span style="color:#2B6B97"> Assignment Survey </span>
@endsection
@section('button')
      <div class="forButtonTop">
          <button href="" class="btn btn-default buttonAE btnTop" onclick="add_assignment_survey()">
              <i class="fa fa-plus" aria-hidden="true"></i> Add New
          </button>
          <a href="" class="btn btn-primary white btnTop" style="margin-left:10px;">
              <i class="fa fa-refresh" aria-hidden="true"></i> Refresh
          </a>
    </div>
@endsection

@section('content')
<section class="content">
    <!-- /.box-header -->
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="tableAssignmentSurvey" class="table table-bordered table-striped">
                            <thead>
                                <tr style="background-color:#8B9AAD;color:#fff">
                                    <th>No</th>
                                    <th>No Survey</th>
                                    <th>Survey Type</th>
                                    <th>Survey Date</th>
                                    <th>AB</th>
                                    <th>PC-EZ</th>
                                    <th>Nomen</th>
                                    <th>Asset</th>
                                    <th>Assign</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Status Survey</th>
                                    <th>Sending</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($list_survey as $key=>$survey)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$survey->survey_code}}</td>
                                    <td>{{$survey->survey_name}}</td>
                                    <td>{{$survey->survey_date}}</td>
                                    <td>{{($survey->code_ab) ? $survey->code_ab : '-'}}
                                    <!-- <button class="btn btn-primary" style="margin-left: 5px;"> <i class="fa fa-search"></i> </button> -->
                                    </td>
                                    <td>{{($survey->code_pc) ? $survey->code_pc : '-'}}{{$survey->code_ez}}
                                    <!-- <button class="btn btn-primary" style="margin-left: 5px;"> <i class="fa fa-search"></i> </button> -->
                                    </td>
                                    <td>{{($survey->nomen) ? $survey->nomen : '-'}}</td>
                                    <td>{{($survey->asset) ? $survey->asset : '-'}}</td>
                                    <td>{{$survey->worker_name}}</td>
                                    <td>{{$survey->start_date}}</td>
                                    <td>{{$survey->end_date}}</td>
                                    <td>{{$survey->survey_status}}</td>
                                    <td>{{$survey->sending_status}}</td>
                                    <td>
                                    <button class="btn btn-success" onclick="editAssignmentSurvey('{{$survey->id}}')"><i class="fa fa-pencil"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box body -->
</section>
<!-- /section -->

<!-- Modal   Add -->
<div class="modal fade" id="modalAssignmentSurvey" tabindex="-1" role="dialog" aria-labelledby="groupModalCenterTitle" aria-hidden="false">
  <div class="modal-dialog modal-dialog-centered  modal-lg" role="document" style="width: 40%;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true" style="color:#fff">&times;</span>
        </button>
        <h4 class="modal-title" style="text-align:center">Assignment Survey</h4>
      </div>
      <div class="modal-body"  style="background-color: #FBFBFB">
       
      </div><!-- / Modal Body -->
      <div class="modal-footer" style="text-align: center">
        <button type="button" class="btn btn-secondary btnFooterModal" data-dismiss="modal" onclick="window.location.reload()">Cancel</button>
        <button type="button" class="btn btn-primary  btnFooterModal" onclick="saveAssignSurvey()">Save</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal View Detail  -->
<div class="modal fade" id="modalViewDetail" tabindex="-1" role="dialog" aria-labelledby="modalViewDetail" aria-hidden="false" >
    <div class="modal-dialog modal-dialog-centered  modal-lg" role="document" style="width: 30%;height: 85%;">
        <div class="modal-content" style="height: auto">
            <div class="modal-header">
                <button type="button" class="close">
                    <span aria-hidden="true" style="color:#fff">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #FBFBFB;max-height: calc(100% -  120px);overflow-y: auto;"></div><!-- / Modal Body -->
            <div class="modal-footer" style="text-align: center"></div>
        </div>
    </div>
</div>
<!-- end View Detail -->
@endsection

@section('js')
  @include('transaction.assignmentSurvey.js_assignmentSurvey')
@endsection

resources/views/transaction/assignmentSurvey/view_detail_ab.blade.php
 <form id="formDetailData">
<table class="table table-striped table-bordered" id="detailData"> 
  <thead>
    <tr>
      <th> Detail AB </th>
    </tr>
  </thead>
  <tbody>
   @foreach($detail_ab as $detail)
    <tr>
      <td width="40%" height="auto">{{($detail->code_ab) ? $detail->code_ab : 'Kosong'}}</td>
    </tr>
    @endforeach
  </tbody>
</table>  
</form>